###
POST http://recettetw.teliway.com/appli/vgtra.preprod/ws/entrant/GestionSAV/gestionSAV.php
Content-Type: application/soap+xml

<SOAP:Envelope
    xmlns:SOAP="http://schemas.xmlsoap.org/soap/envelope/"
    >
    			<SOAP:Header>
        		<AuthentificationHeader>        
        			<sLogin>gtraws</sLogin>
        			<sPassword>mac#Pr0v1</sPassword>        
        		</AuthentificationHeader>        
        	</SOAP:Header>
    <SOAP:Body>
		<creerModifierReclamation>
			<infosCreationModificationReclamation>
				<idPosition>11968785</idPosition>
				<iNumero>007</iNumero>
				<sTypeReclamation>Avarie</sTypeReclamation>
				<iOrigine>1</iOrigine>
				<iStatut>0</iStatut>
				<sNomContact>TEST</sNomContact>
				<sMotifCreation>TEST création réclamation</sMotifCreation>
				<sLoginOuverture>extranet</sLoginOuverture>
			</infosCreationModificationReclamation>
		</creerModifierReclamation>
    </SOAP:Body>
</SOAP:Envelope>

###
POST http://gtra.teliway.com/appli/vgtra/ws/entrant/GestionPosition/gestionPosition.php
Content-Type: application/soap+xml

<SOAP:Envelope
    xmlns:SOAP="http://schemas.xmlsoap.org/soap/envelope/"
    >
    			<SOAP:Header>
        		<AuthentificationHeader>        
        			<sLogin>gtraws</sLogin>
        			<sPassword>mac#Pr0v1</sPassword>        
        		</AuthentificationHeader>        
        	</SOAP:Header>
    <SOAP:Body>
		<pointerPosition>
			<pointagePositionDemande>
				<tabIdPosition><item>11843232</item></tabIdPosition>
                <sCodeEvenement>INFPAL</sCodeEvenement>
				<iOrigine>1</iOrigine>
                <dtmDateHeureEvenement>2025-08-14T11:00:00</dtmDateHeureEvenement>
                <sCodeTiersEmetteur>95S</sCodeTiersEmetteur>
                <sInfoPalettesRendues>3</sInfoPalettesRendues>
			</pointagePositionDemande>
		</pointerPosition>
    </SOAP:Body>
</SOAP:Envelope>

